### PR TITLE
Added ITrustProvider and default implementation

### PR DESCRIPTION
**Pull request by vincentparrett**
The PR makes it possible to externalise the management of client thumprint trust, which makes it easier to manage trust without exposing the runtime instance in places where it's not really needed.  

BTW, I updated the public surface tests with the changes, not sure if was something I should do or should leave for you, but seemed like bad form to push failing tests so I went ahead and did it anyway. The interface changes should still be backwards compatible.

### CODE REVIEW

**Comment by vincentparrett** [comment]
This implements the suggestion in #70

**Comment by vincentparrett** [comment]
PR #80  messes up this PR - I moved the locking around the trustedThumbprints inside the trustProvider - however you just added more code inside the lock. I need some guidance here as it's no longer a simple change.

**Comment by vincentparrett** [comment]
One option is to change the ITrustProvider interface so the methods take an action to run in the lock

````c#
public interface ITrustProvider
{
    void Add(string clientThumbprint, Action onChanged);
...
}
````
Then the implementation needs to call the action
````C#
public void Add(string clientThumbprint, Action onChange = null)
{
    lock (trustedThumbprints)
    {
       trustedThumbprints.Add(clientThumbprint);
       onChange?.Invoke();
    }
}
`````
The trouble there is that is relying on the implementer on ITrustProvider to do the right thing. 
Thoughts?

**Comment by tothegills** [comment]
I wonder if we can do it without a callback?

I don't think `DisconnectFromAllListeners` needs to be inside the lock. `RemoveTrust` is straightforward:
```
        public void RemoveTrust(string clientThumbprint)
        {
            trustProvider.Remove(clientThumbprint);
            DisconnectFromAllListeners(clientThumbprint);
        }
```

`TrustOnly` is a bit more complicated, `DisconnectFromAllListeners` wants to know which thumbprints have had trust revoked which is currently difficult to do via `ITrustProvider`.

**Comment by vincentparrett** [comment]
What about adding a ToArray method to the trustProvider

````c#
       public string[] ToArray()
        {
            lock (trustedThumbprints)
            {
                return trustedThumbprints.ToArray();
            }
        }
````
Then TrustOnly can be something like this 

`````c#
        public void TrustOnly(IReadOnlyList<string> thumbprints)
        {
            var thumbprintsRevoked = trustProvider.ToArray().Except(thumbprints).ToArray();
            trustProvider.TrustOnly(thumbprints);
            DisconnectFromAllListeners(thumbprintsRevoked);
        }
`````

**Comment by tothegills** [comment]
I think that approach is reasonable. Do you want to update the PR and I will merge?

**Comment by vincentparrett** [comment]
Yep will do.

**Comment by tothegills** [comment]
Merged in #81

**Pull request closed without merging**
